name = "smakfynd-auth"
main = "worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "smakfynd-users"
database_id = "6c6b2fa4-043d-4bf6-97b5-92d8bf4b0382"

[vars]
ALLOWED_ORIGIN = "https://smakfynd.se"
